apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-reisetilskudd-gsak
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 20m
      memory: 50Mi
  accessPolicy:
    outbound:
      rules:
        - application: flex-reisetilskudd-pdfgen

