apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-reisetilskudd-gsak
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 100Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: flex-reisetilskudd-gsak-db
            diskAutoresize: true
  accessPolicy:
    outbound:
      rules:
        - application: flex-reisetilskudd-pdfgen
  azure:
    application:
      enabled: true
  env:
    - name: FLEX_FSS_PROXY_AAD_CLIENT_ID
      value: "97abc02f-820c-4c6f-a25a-ec19ac7cae8c"
