CREATE TABLE INNSENDING
(
    REISETILSKUDD_ID VARCHAR(36)              NOT NULL PRIMARY KEY,
    FNR              VARCHAR(11)              NOT NULL,
    SAKS_ID          VARCHAR(20)              NOT NULL,
    JOURNALPOST_ID   VARCHAR(20)              NOT NULL,
    OPPRETTET        TIMESTAMP WITH TIME ZONE NOT NULL
);
