DROP TABLE INNSENDING;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE INNSENDING
(
    ID               VARCHAR(36) DEFAULT uuid_generate_v4() PRIMARY KEY,
    REISETILSKUDD_ID VARCHAR(36)              NOT NULL UNIQUE,
    FNR              VARCHAR(11)              NOT NULL,
    SAKS_ID          VARCHAR(20)              NOT NULL,
    JOURNALPOST_ID   VARCHAR(20)              NOT NULL,
    OPPRETTET        TIMESTAMP WITH TIME ZONE NOT NULL
);
